name: Main Workflow

on: [push, pull_request]

jobs:
  run:
    name: Run

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]
        node: [14.19.0, 16, 17, 18]

    steps:
      - name: Checkout code
        uses: actions/checkout@master

      - name: Setup Node.js
        uses: actions/setup-node@master
        with:
          node-version: ${{ matrix.node }}

      - name: Setup pnpm
        run: npm install pnpm -g

      - name: Install
        run: pnpm install

      - name: Lint
        run: pnpm run lint

      - name: Test
        run: pnpm test

  release:
    needs: run
    runs-on: ubuntu-latest
    if:
      ${{ github.event_name == 'push' && contains('refs/heads/main,refs/heads/beta,refs/heads/alpha', github.ref) }}
    steps:
      - name: Checkout code
        uses: actions/checkout@master
      - name: Setup pnpm
        run: npm install pnpm -g
      - name: Install
        run: pnpm install
      - name: Build
        run: pnpm build
      - name: Release
        uses: ph-fritsche/action-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
